numbers =[5, 2, 7, 1, 7, 7, 4]
print('count 7: ', numbers.count(7))
numbers.append(20)
print('append: ', numbers)
numbers.insert(0, 10)
print('insert 10 at index 0: ', numbers)
numbers.remove(7)
print('remove 7: ', numbers)
numbers.pop()
print('pop last number: ', numbers)
print('index of 7: ', numbers.index(7))
print('index of 99: ', 99 in numbers)
numbers.sort()
print('sort in place: ', numbers)
numbers.reverse()
print('reverse in place: ', numbers)
numbers2 = numbers.copy()
numbers.append(11)
print("numbers2: ", numbers2, numbers)
numbers.clear()
print('clear: ', numbers)
# print(help(numbers))